# ＠＠
# dein.toml

# 置換のプレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# ステータスバー
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode
  let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'mode_map': {'c': 'NORMAL'},
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
      \ },
      \ 'component_function': {
      \   'modified': 'LightlineModified',
      \   'readonly': 'LightlineReadonly',
      \   'fugitive': 'LightlineFugitive',
      \   'filename': 'LightlineFilename',
      \   'fileformat': 'LightlineFileformat',
      \   'filetype': 'LightlineFiletype',
      \   'fileencoding': 'LightlineFileencoding',
      \   'mode': 'LightlineMode'
      \ },
      \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
      \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
      \ }

  function! LightlineModified()
    return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
  endfunction

  function! LightlineReadonly()
    return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
  endfunction

  function! LightlineFilename()
    return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
      \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
      \  &ft == 'unite' ? unite#get_status_string() :
      \  &ft == 'vimshell' ? vimshell#get_status_string() :
      \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
      \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
  endfunction

  function! LightlineFugitive()
    if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
      return fugitive#head()
    else
      return ''
    endif
  endfunction

  function! LightlineFileformat()
    return winwidth(0) > 70 ? &fileformat : ''
  endfunction

  function! LightlineFiletype()
    return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
  endfunction

  function! LightlineFileencoding()
    return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
  endfunction

  function! LightlineMode()
    return winwidth(0) > 60 ? lightline#mode() : ''
  endfunction
'''

# カラースキーマ
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  autocmd VimEnter * ++nested colorscheme tender

  " set lighline theme inside lightline config
  let g:lightline = { 'colorscheme': 'tender' }
'''

# ファイラ
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR>

  " 引数なしでvimを開いたらNERDTreeを起動、
  " 引数ありならNERDTreeは起動せず、引数で渡されたファイルを開く。
  autocmd vimenter * if !argc() | NERDTree | endif

  " 他のバッファをすべて閉じた時にNERDTreeが開いていたらNERDTreeも一緒に閉じる。
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

  " 隠しファイルをデフォルトで表示させる
  let g:NERDTreeShowHidden = 1

  " 以下のファイルは vim からは見たくない
  let g:NERDTreeIgnore = ['\~$', '.pdf$', '.xlsx$', '.xd$', '.psd$', '.jpg$', '.gif$', '.png$', '.zip$', '.tar$', '.tz$', '.tgz$', '.exe$', '.o$', '.so$', '.lnk$', '^ntuser', '^NTUSER']

  " Bookmarkをデフォルトで表示させる
  let g:NERDTreeShowBookmarks=1

  " NERDTreeでルートを変更したらchdirする
  let g:NERDTreeChDirMode = 2
'''
# 多機能セレクタ
[[plugins]]
repo = 'kien/ctrlp.vim'

# NERDTreeやCtrlPにDevIconsを適用
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# NERDTreeに色分けを適用
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

